FervorFieldCity_ARHU_MapScripts::
	.byte 0

@ Local copies of FuchsiaCity_Frlg scripts (FRLG originals are IS_FRLG-only)

FervorFieldCity_ARHU_EventScript_LittleBoy::
	msgbox FervorFieldCity_ARHU_Text_DidYouTrySafariGame, MSGBOX_NPC
	end

FervorFieldCity_ARHU_EventScript_OldMan::
	msgbox FervorFieldCity_ARHU_Text_SafariZoneZooInFront, MSGBOX_NPC
	end

FervorFieldCity_ARHU_EventScript_Erik::
	msgbox FervorFieldCity_ARHU_Text_WheresSara, MSGBOX_NPC
	end

FervorFieldCity_ARHU_EventScript_Youngster::
	msgbox FervorFieldCity_ARHU_Text_ItemBallInThere, MSGBOX_NPC
	end

FervorFieldCity_ARHU_EventScript_SubstituteTutor::
	msgbox FervorFieldCity_ARHU_Text_SubstituteTutor, MSGBOX_NPC
	end

FervorFieldCity_ARHU_EventScript_CitySign::
	msgbox FervorFieldCity_ARHU_Text_CitySign, MSGBOX_SIGN
	end

FervorFieldCity_ARHU_EventScript_SafariZoneSign::
	msgbox FervorFieldCity_ARHU_Text_SafariZoneSign, MSGBOX_SIGN
	end

FervorFieldCity_ARHU_EventScript_SafariGameSign::
	msgbox FervorFieldCity_ARHU_Text_SafariGameSign, MSGBOX_SIGN
	end

FervorFieldCity_ARHU_EventScript_WardensHomeSign::
	msgbox FervorFieldCity_ARHU_Text_WardensHomeSign, MSGBOX_SIGN
	end

FervorFieldCity_ARHU_EventScript_GymSign::
	msgbox FervorFieldCity_ARHU_Text_GymSign, MSGBOX_SIGN
	end

FervorFieldCity_ARHU_Text_DidYouTrySafariGame::
	.string "Did you try the SAFARI GAME?\p"
	.string "There are some rare POKéMON that\n"
	.string "can only be caught there.$"

FervorFieldCity_ARHU_Text_SafariZoneZooInFront::
	.string "The SAFARI ZONE has a zoo in front\n"
	.string "of the entrance.\p"
	.string "Out back is the SAFARI GAME for\n"
	.string "catching POKéMON.$"

FervorFieldCity_ARHU_Text_WheresSara::
	.string "ERIK: Where's SARA?\n"
	.string "I said I'd meet her here.$"

FervorFieldCity_ARHU_Text_ItemBallInThere::
	.string "That item ball in there…\n"
	.string "Were you wanting that?\p"
	.string "Me, too!\n"
	.string "…Huh? That's a POKéMON?$"

FervorFieldCity_ARHU_Text_SubstituteTutor::
	.string "I can teach a POKéMON how to use\n"
	.string "SUBSTITUTE…\p"
	.string "But I'm taking a break right now.$"

FervorFieldCity_ARHU_Text_CitySign::
	.string "FUCHSIA CITY\n"
	.string "Behold! It's Passion Pink!$"

FervorFieldCity_ARHU_Text_SafariZoneSign::
	.string "POKéMON PARADISE\n"
	.string "SAFARI ZONE$"

FervorFieldCity_ARHU_Text_SafariGameSign::
	.string "SAFARI GAME\n"
	.string "POKéMON-U-CATCH!$"

FervorFieldCity_ARHU_Text_WardensHomeSign::
	.string "SAFARI ZONE\n"
	.string "WARDEN'S HOME$"

FervorFieldCity_ARHU_Text_GymSign::
	.string "FUCHSIA CITY POKéMON GYM\n"
	.string "LEADER: KOGA\l"
	.string "The Poisonous Ninja Master$"
